data_root: "/fs/vulcan-projects/fsh_track/jason-bhargav-temp/CMSC472-Final/data"
dataset: "SEED-IV"
val_subject: 1

nb_classes: 4
n_subjects: 15
chans: 62
samples: 5

loss_mode: "sepc"
epochs: 100
n_per_class: 8

lr: 0.001
weight_decay: 0.0001
lambda_con: 0.5
temperature: 0.1
ema_alpha: 0.9
warmup_epochs: 5

seed: 42
